[package]
name = "mongo-tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.6.0"
tracing = "0.1.37"
serde = "1.0.183"
